/* NexaDash — peta rute halaman.
   Kunci = nama kanonik yang dipakai di dalam body/partial (tetap datar, mudah dicari),
   nilai = lokasi file sebenarnya setelah dikelompokkan ke dalam folder.
   build.js menerjemahkan setiap href/src ke path relatif yang benar per halaman,
   sehingga template tetap berfungsi dibuka langsung lewat file:// maupun http. */
module.exports = {
  'index.html': 'index.html',

  'dashboard-analytics.html': 'dashboards/analytics.html',
  'dashboard-ecommerce.html': 'dashboards/ecommerce.html',
  'dashboard-crm.html': 'dashboards/crm.html',
  'dashboard-clinical.html': 'dashboards/clinical.html',

  'chart-apex.html': 'charts/apexcharts.html',
  'chart-chartjs.html': 'charts/chartjs.html',
  'chart-sparkline.html': 'charts/sparkline.html',

  'apps-mail.html': 'apps/mail.html',
  'apps-chat.html': 'apps/chat.html',
  'apps-files.html': 'apps/files.html',
  'apps-kanban.html': 'apps/kanban.html',
  'apps-calendar.html': 'apps/calendar.html',
  'apps-wizard.html': 'apps/wizard.html',

  'commerce-orders.html': 'commerce/orders.html',
  'commerce-products.html': 'commerce/products.html',
  'commerce-product-detail.html': 'commerce/product-detail.html',
  'commerce-customers.html': 'commerce/customers.html',
  'commerce-invoices.html': 'commerce/invoices.html',
  'commerce-invoice-detail.html': 'commerce/invoice-detail.html',

  'ui-buttons.html': 'ui/buttons.html',
  'ui-cards.html': 'ui/cards.html',
  'ui-modals.html': 'ui/modals.html',
  'ui-tabs-accordions.html': 'ui/tabs-accordions.html',
  'ui-alerts-badges.html': 'ui/alerts-badges.html',
  'ui-progress-spinners.html': 'ui/progress-spinners.html',
  'ui-tooltips-popovers.html': 'ui/tooltips-popovers.html',
  'ui-toasts-notifications.html': 'ui/toasts.html',
  'ui-dropdowns.html': 'ui/dropdowns.html',
  'ui-avatars-images.html': 'ui/avatars-images.html',
  'ui-pagination-breadcrumbs.html': 'ui/pagination-breadcrumbs.html',
  'ui-list-group-timeline.html': 'ui/list-group-timeline.html',
  'ui-offcanvas-placeholders.html': 'ui/offcanvas-placeholders.html',
  'ui-typography.html': 'ui/typography.html',
  'ui-icons.html': 'ui/icons.html',
  'ui-colors.html': 'ui/colors.html',

  'form-elements.html': 'forms/elements.html',
  'form-layouts.html': 'forms/layouts.html',
  'form-validation.html': 'forms/validation.html',
  'form-select2.html': 'forms/select2.html',
  'form-pickers.html': 'forms/pickers.html',
  'form-editors.html': 'forms/editors.html',
  'form-upload.html': 'forms/upload.html',
  'form-input-mask.html': 'forms/input-mask.html',

  'plugin-index.html': 'plugins/index.html',
  'plugin-maps.html': 'plugins/maps.html',
  'plugin-data-grids.html': 'plugins/data-grids.html',
  'plugin-media.html': 'plugins/media.html',
  'plugin-inputs.html': 'plugins/inputs.html',
  'plugin-documents.html': 'plugins/documents.html',
  'plugin-ux.html': 'plugins/ux.html',
  'plugin-layout.html': 'plugins/layout.html',
  'plugin-utilities.html': 'plugins/utilities.html',
  'plugin-diagrams.html': 'plugins/diagrams.html',
  'plugin-org-chart.html': 'plugins/org-chart.html',

  'dashboard-academy.html': "dashboards/academy.html",
  'dashboard-logistics.html': "dashboards/logistics.html",
  'dashboard-support.html': "dashboards/support.html",
  'dashboard-project.html': "dashboards/project.html",
  'apps-social.html': "apps/social.html",
  'apps-contacts.html': "apps/contacts.html",
  'apps-notes.html': "apps/notes.html",
  'apps-tickets.html': "apps/tickets.html",
  'apps-ticket-detail.html': "apps/ticket-detail.html",
  'apps-events.html': "apps/events.html",
  'apps-event-detail.html': "apps/event-detail.html",
  'apps-courses.html': "apps/courses.html",
  'apps-course-detail.html': "apps/course-detail.html",
  'commerce-product-add.html': "commerce/product-add.html",
  'commerce-categories.html': "commerce/categories.html",
  'commerce-order-detail.html': "commerce/order-detail.html",
  'commerce-customer-detail.html': "commerce/customer-detail.html",
  'commerce-cart.html': "commerce/cart.html",
  'commerce-checkout.html': "commerce/checkout.html",
  'commerce-reviews.html': "commerce/reviews.html",
  'ui-carousel.html': "ui/carousel.html",
  'ui-navbar-footer.html': "ui/navbar-footer.html",
  'ui-ratings.html': "ui/ratings.html",
  'ui-media-player.html': "ui/media-player.html",
  'ui-treeview.html': "ui/treeview.html",
  'ui-blockui.html': "ui/blockui.html",
  'ui-stat-cards.html': "ui/stat-cards.html",
  'form-custom-options.html': "forms/custom-options.html",
  'form-sticky-actions.html': "forms/sticky-actions.html",
  'page-roles.html': "pages/roles.html",
  'page-permissions.html': "pages/permissions.html",
  'page-user-detail.html': "pages/user-detail.html",
  'page-teams.html': "pages/teams.html",
  'page-projects.html': "pages/projects.html",
  'page-connections.html': "pages/connections.html",
  'page-help-center.html': "pages/help-center.html",
  'page-landing.html': "pages/landing.html",
  'page-starter.html': "pages/starter.html",
  'page-payment.html': "pages/payment.html",
  'page-level-two.html': "pages/level-two.html",
  'page-level-three.html': "pages/level-three.html",
  'auth-verify-email.html': "auth/verify-email.html",
  'auth-reset-password.html': "auth/reset-password.html",
  'error-401.html': "errors/401.html",
  'error-coming-soon.html': "errors/coming-soon.html",
  'layout-horizontal.html': "layouts/horizontal.html",
  'layout-blank.html': "layouts/blank.html",
  'layout-fluid.html': "layouts/fluid.html",

  'table-basic.html': 'tables/basic.html',
  'table-datatables.html': 'tables/datatables.html',

  'page-profile.html': 'pages/profile.html',
  'page-settings.html': 'pages/settings.html',
  'page-pricing.html': 'pages/pricing.html',
  'page-faq.html': 'pages/faq.html',
  'page-timeline.html': 'pages/timeline.html',
  'page-users.html': 'pages/users.html',
  'page-notifications.html': 'pages/notifications.html',
  'page-roadmap.html': 'pages/roadmap.html',
  'page-activity.html': 'pages/activity.html',
  'page-changelog.html': 'pages/changelog.html',

  'auth-login.html': 'auth/login.html',
  'auth-register.html': 'auth/register.html',
  'auth-forgot-password.html': 'auth/forgot-password.html',
  'auth-lock-screen.html': 'auth/lock-screen.html',
  'auth-two-factor.html': 'auth/two-factor.html',

  'error-404.html': 'errors/404.html',
  'error-500.html': 'errors/500.html',
  'error-maintenance.html': 'errors/maintenance.html'
};
